    spec:
      volumes:
        - name: loader-config-volume
          configMap:
            name: loader-config
            defaultMode: 420
      containers:
        - name: loader
          image: node:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: loader-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
