---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: connector
  labels:
    app: connector

spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      containers:
        - name: connector
          image: deployerr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            # requests:
            #   cpu: 100m
            #   memory: 200Mi
            limits:
              cpu: 1
              memory: 128Mi
