    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
       # haproxy.router.openshift.io/timeout: 2m    #setting timeouts
       # haproxy.router.openshift.io/ip_whitelist: 192.168.1.10  exposing routes to specific ips
        openshift.io/host.generated: 'true'
      name: 'chat-supedddrman'
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: 'chat-superman'
        weight: 100
      wildcardPolicy: None
